services:
  mysqldb:
    image: mysql:latest
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: event
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAG: dev
      SERVICE_NAME: mysqldb
    networks:
      - eventnetwork

networks:
  eventnetwork:
    driver: bridge

volumes:
  database:
